# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_rst_clk_wiz_1_100M_0/design_CPU_System_rst_clk_wiz_1_100M_0.xci
# IP: The module: 'design_CPU_System_rst_clk_wiz_1_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_rst_clk_wiz_1_100M_0/design_CPU_System_rst_clk_wiz_1_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_CPU_System_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_rst_clk_wiz_1_100M_0/design_CPU_System_rst_clk_wiz_1_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_CPU_System_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_rst_clk_wiz_1_100M_0/design_CPU_System_rst_clk_wiz_1_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_CPU_System_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_rst_clk_wiz_1_100M_0/design_CPU_System_rst_clk_wiz_1_100M_0.xci
# IP: The module: 'design_CPU_System_rst_clk_wiz_1_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_rst_clk_wiz_1_100M_0/design_CPU_System_rst_clk_wiz_1_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_CPU_System_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_rst_clk_wiz_1_100M_0/design_CPU_System_rst_clk_wiz_1_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_CPU_System_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_rst_clk_wiz_1_100M_0/design_CPU_System_rst_clk_wiz_1_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_CPU_System_rst_clk_wiz_1_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
