# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/design_CPU_System_system_ila_0.xci
# IP: The module: 'design_CPU_System_system_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/bd_addd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd || ORIG_REF_NAME==bd_addd}]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_0/bd_addd_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd_ila_lib_0 || ORIG_REF_NAME==bd_addd_ila_lib_0}]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_1/bd_addd_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd_g_inst_0 || ORIG_REF_NAME==bd_addd_g_inst_0}]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_2/bd_addd_slot_1_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd_slot_1_aw_0 || ORIG_REF_NAME==bd_addd_slot_1_aw_0}]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_3/bd_addd_slot_1_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd_slot_1_w_0 || ORIG_REF_NAME==bd_addd_slot_1_w_0}]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_4/bd_addd_slot_1_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd_slot_1_b_0 || ORIG_REF_NAME==bd_addd_slot_1_b_0}]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_5/bd_addd_slot_1_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd_slot_1_ar_0 || ORIG_REF_NAME==bd_addd_slot_1_ar_0}]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_6/bd_addd_slot_1_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd_slot_1_r_0 || ORIG_REF_NAME==bd_addd_slot_1_r_0}]

# XDC: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_addd_ila_lib_0 || ORIG_REF_NAME==bd_addd_ila_lib_0}] {/inst }]/inst ]]

# XDC: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_0/bd_addd_ila_lib_0_ooc.xdc

# XDC: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_1/bd_addd_g_inst_0_ooc.xdc

# XDC: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/bd_addd_ooc.xdc

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/design_CPU_System_system_ila_0.xci
# IP: The module: 'design_CPU_System_system_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/bd_addd.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd || ORIG_REF_NAME==bd_addd}]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_0/bd_addd_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd_ila_lib_0 || ORIG_REF_NAME==bd_addd_ila_lib_0}]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_1/bd_addd_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd_g_inst_0 || ORIG_REF_NAME==bd_addd_g_inst_0}]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_2/bd_addd_slot_1_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd_slot_1_aw_0 || ORIG_REF_NAME==bd_addd_slot_1_aw_0}]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_3/bd_addd_slot_1_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd_slot_1_w_0 || ORIG_REF_NAME==bd_addd_slot_1_w_0}]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_4/bd_addd_slot_1_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd_slot_1_b_0 || ORIG_REF_NAME==bd_addd_slot_1_b_0}]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_5/bd_addd_slot_1_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd_slot_1_ar_0 || ORIG_REF_NAME==bd_addd_slot_1_ar_0}]

# IP: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_6/bd_addd_slot_1_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_addd_slot_1_r_0 || ORIG_REF_NAME==bd_addd_slot_1_r_0}]

# XDC: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_addd_ila_lib_0 || ORIG_REF_NAME==bd_addd_ila_lib_0}] {/inst }]/inst ]]

# XDC: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_0/bd_addd_ila_lib_0_ooc.xdc

# XDC: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_1/bd_addd_g_inst_0_ooc.xdc

# XDC: d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/bd_addd_ooc.xdc
