# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Vivado/digital_circuits/Mini_System/Mini_System.cache/wt [current_project]
set_property parent.project_path D:/Vivado/digital_circuits/Mini_System/Mini_System.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
set_property ip_output_repo d:/Vivado/digital_circuits/Mini_System/Mini_System.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/hdl/design_CPU_System_wrapper.v
add_files D:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/design_CPU_System.bd
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_microblaze_0_0/design_CPU_System_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_microblaze_0_0/design_CPU_System_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_microblaze_0_0/design_CPU_System_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_dlmb_v10_0/design_CPU_System_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_dlmb_v10_0/design_CPU_System_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_ilmb_v10_0/design_CPU_System_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_ilmb_v10_0/design_CPU_System_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_dlmb_bram_if_cntlr_0/design_CPU_System_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_ilmb_bram_if_cntlr_0/design_CPU_System_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_lmb_bram_0/design_CPU_System_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_mdm_1_0/design_CPU_System_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_mdm_1_0/design_CPU_System_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_mdm_1_0/design_CPU_System_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_clk_wiz_1_0/design_CPU_System_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_clk_wiz_1_0/design_CPU_System_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_clk_wiz_1_0/design_CPU_System_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_rst_clk_wiz_1_100M_0/design_CPU_System_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_rst_clk_wiz_1_100M_0/design_CPU_System_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_rst_clk_wiz_1_100M_0/design_CPU_System_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_uartlite_0_0/design_CPU_System_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_uartlite_0_0/design_CPU_System_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_uartlite_0_0/design_CPU_System_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_gpio_0_0/design_CPU_System_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_gpio_0_0/design_CPU_System_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_gpio_0_0/design_CPU_System_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_gpio_1_0/design_CPU_System_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_gpio_1_0/design_CPU_System_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_gpio_1_0/design_CPU_System_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_gpio_2_0/design_CPU_System_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_gpio_2_0/design_CPU_System_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_gpio_2_0/design_CPU_System_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_xbar_0/design_CPU_System_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_intc_0_0/design_CPU_System_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_intc_0_0/design_CPU_System_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_intc_0_0/design_CPU_System_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_timer_0_0/design_CPU_System_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_timer_0_0/design_CPU_System_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_uartlite_1_0/design_CPU_System_axi_uartlite_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_uartlite_1_0/design_CPU_System_axi_uartlite_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_uartlite_1_0/design_CPU_System_axi_uartlite_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_uartlite_2_0/design_CPU_System_axi_uartlite_2_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_uartlite_2_0/design_CPU_System_axi_uartlite_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_uartlite_2_0/design_CPU_System_axi_uartlite_2_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_quad_spi_0_0/design_CPU_System_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_quad_spi_0_0/design_CPU_System_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_quad_spi_0_0/design_CPU_System_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_quad_spi_0_0/design_CPU_System_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_quad_spi_1_0/design_CPU_System_axi_quad_spi_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_quad_spi_1_0/design_CPU_System_axi_quad_spi_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_quad_spi_1_0/design_CPU_System_axi_quad_spi_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_axi_quad_spi_1_0/design_CPU_System_axi_quad_spi_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_0/bd_addd_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/ip/ip_1/bd_addd_g_inst_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_system_ila_0/bd_0/bd_addd_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_auto_pc_0/design_CPU_System_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/design_CPU_System_ooc.xdc]
set_property is_locked true [get_files D:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/sources_1/bd/design_CPU_System/design_CPU_System.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/constrs_1/new/Mini.xdc
set_property used_in_implementation false [get_files D:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/constrs_1/new/Mini.xdc]

read_xdc D:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/constrs_1/new/adda.xdc
set_property used_in_implementation false [get_files D:/Vivado/digital_circuits/Mini_System/Mini_System.srcs/constrs_1/new/adda.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_CPU_System_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef design_CPU_System_wrapper.dcp

catch { report_utilization -file design_CPU_System_wrapper_utilization_synth.rpt -pb design_CPU_System_wrapper_utilization_synth.pb }
