# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Mini.xdc

# XDC: new/adda.xdc

# Block Designs: bd/design_CPU_System/design_CPU_System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System || ORIG_REF_NAME==design_CPU_System}]

# IP: bd/design_CPU_System/ip/design_CPU_System_microblaze_0_0/design_CPU_System_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_microblaze_0_0 || ORIG_REF_NAME==design_CPU_System_microblaze_0_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_dlmb_v10_0/design_CPU_System_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_dlmb_v10_0 || ORIG_REF_NAME==design_CPU_System_dlmb_v10_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_ilmb_v10_0/design_CPU_System_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_ilmb_v10_0 || ORIG_REF_NAME==design_CPU_System_ilmb_v10_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_dlmb_bram_if_cntlr_0/design_CPU_System_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_CPU_System_dlmb_bram_if_cntlr_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_ilmb_bram_if_cntlr_0/design_CPU_System_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_CPU_System_ilmb_bram_if_cntlr_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_lmb_bram_0/design_CPU_System_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_lmb_bram_0 || ORIG_REF_NAME==design_CPU_System_lmb_bram_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_mdm_1_0/design_CPU_System_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_mdm_1_0 || ORIG_REF_NAME==design_CPU_System_mdm_1_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_clk_wiz_1_0/design_CPU_System_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_clk_wiz_1_0 || ORIG_REF_NAME==design_CPU_System_clk_wiz_1_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_rst_clk_wiz_1_100M_0/design_CPU_System_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==design_CPU_System_rst_clk_wiz_1_100M_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_uartlite_0_0/design_CPU_System_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_uartlite_0_0 || ORIG_REF_NAME==design_CPU_System_axi_uartlite_0_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_microblaze_0_axi_periph_0/design_CPU_System_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_CPU_System_microblaze_0_axi_periph_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_gpio_0_0/design_CPU_System_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_gpio_0_0 || ORIG_REF_NAME==design_CPU_System_axi_gpio_0_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_gpio_1_0/design_CPU_System_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_gpio_1_0 || ORIG_REF_NAME==design_CPU_System_axi_gpio_1_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_gpio_2_0/design_CPU_System_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_gpio_2_0 || ORIG_REF_NAME==design_CPU_System_axi_gpio_2_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_xbar_0/design_CPU_System_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_xbar_0 || ORIG_REF_NAME==design_CPU_System_xbar_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_intc_0_0/design_CPU_System_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_intc_0_0 || ORIG_REF_NAME==design_CPU_System_axi_intc_0_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_xlconcat_0_0/design_CPU_System_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_xlconcat_0_0 || ORIG_REF_NAME==design_CPU_System_xlconcat_0_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_timer_0_0/design_CPU_System_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_timer_0_0 || ORIG_REF_NAME==design_CPU_System_axi_timer_0_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_uartlite_1_0/design_CPU_System_axi_uartlite_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_uartlite_1_0 || ORIG_REF_NAME==design_CPU_System_axi_uartlite_1_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_uartlite_2_0/design_CPU_System_axi_uartlite_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_uartlite_2_0 || ORIG_REF_NAME==design_CPU_System_axi_uartlite_2_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_quad_spi_0_0/design_CPU_System_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_quad_spi_0_0 || ORIG_REF_NAME==design_CPU_System_axi_quad_spi_0_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_quad_spi_1_0/design_CPU_System_axi_quad_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_quad_spi_1_0 || ORIG_REF_NAME==design_CPU_System_axi_quad_spi_1_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_system_ila_0/design_CPU_System_system_ila_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_system_ila_0 || ORIG_REF_NAME==design_CPU_System_system_ila_0}]

# IP: bd/design_CPU_System/ip/design_CPU_System_auto_pc_0/design_CPU_System_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_CPU_System_auto_pc_0 || ORIG_REF_NAME==design_CPU_System_auto_pc_0}]

# XDC: bd/design_CPU_System/design_CPU_System_ooc.xdc
